name: Deploy to EC2

on:
  push:
    branches:
      - "main"
    paths:
      - "3prueba_solution/index.html"  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/devops-interview-solutions/3prueba_solution
            git pull origin main
            docker-compose down
            docker-compose up -d --build


